### PR TITLE
Extend JavaScripty to support all primitives and binding

### PR DESCRIPTION
**Pull request by bechang**
The net result of this feature is a JavaScripty language with all primitive values (numbers, booleans, strings) with variable binding.

@kyleheadley @bennostein There are probably parts that could documented better. Please take a look and let me know.

### CODE REVIEW

**Comment by bechang** [comment]
@bennostein @kyleheadley This should be a pretty small PR to look at.

**Comment by kyleheadley** [comment]
It looks like this is mainly refactoring (with tighter integration of ops), and inclusion of the string primitive. It looks fine to me. Many prior refactorings came about naturally as we understood scala better. Was there any specific improvement intended with this refactoring?

**Comment by bennostein** [comment]
LGTM.   I also didn't see anything too game-changing in this PR, but looks like a solid collection of refactorings.

**Review by bennostein — APPROVED** [review]

**Comment by bechang** [comment]
@kyleheadley Like I said, it is a pretty small PR. Fairly incremental changes. I wanted to close out primitives before moving on.

**Pull request merged**
