### PR TITLE
Modularizing arithmetic interpreter

### PR DESCRIPTION
**Pull request by bechang**
I have some sketches of possible modularizations of the arithmetic interpreter. This pull request is to start a discussion about it.

### CODE REVIEW

**Comment by bennostein** [comment]
I really like this ML-style modularization - I think using Scala traits like ML sigs is a great design pattern.  It's quite similar to how I modularized AIWala abstract domains last year, but takes everything a step further, particularly with the explicit denotation into a FixFun.

LGTM

**Comment by bechang** [comment]
There are some in-between versions depending on whether you want to use an abstract type or type parameter, but that's relatively minor, as you can convert between the two pretty easily. I think it just a matter of what is the more common use-case. That's a flexibility you have with Scala traits that you don't have in ML signatures.

It is also nice that you can provide default implementations in Scala traits.

**Comment by bechang** [comment]
Thanks for the discussion. This is now in a clean state ready for review. 

We should probably converge on #10 first for merging, but I think reviewing in parallel is fine.

**Comment by bechang** [comment]
@bennostein You said that this looks good to you awhile back, but we didn't merge for some reason. Still the case?

**Comment by bennostein** [comment]
Testing slack notifications @benno.stein

**Review by bennostein — APPROVED** [review]
LGTM

**Pull request merged**
