### PR TITLE
Merge WALA client from Aiwala

### PR DESCRIPTION
**Pull request by bechang**
As part of our goal of using cuanto as the place we build interfaces for analysis tools, I wanted to merge in the development of a WALA client from the previous Aiwala efforts.

I don't think we will spend more cycles on WALA for the moment, but I don't want to lose those efforts. And there are projects in the lab using WALA.

### CODE REVIEW

**Comment by bechang** [comment]
After importing from Aiwala, I bumped the version of Wala to 1.4.2. And then, I made the fixes to be compatible with the newer Wala version.

**Review by tianhan0 — COMMENTED** [review]
The code looks nice to me. One minor point is that, in function `fromJavaBinary`, actually Wala provides an API (this is a newly introduced API) that creates an analysis scope: `AnalysisScopeReader.makeJavaBinaryAnalysisScope`. What's more, with this function, we could tell Wala which classes (e.g. java.swing.*, java.awt.*) not to analyze by providing a plain text file.

**Review by tianhan0 — COMMENTED** [review]
After reading [Pimp My Library](https://coderwall.com/p/k_1jzw/scala-s-pimp-my-library-pattern-example), I have a good understanding of why and how pimp classes are useful. Personally I believe the little bit of runtime overhead (of creating a new object) is worthwhile, concerning the simplicity introduced for writing code.

**Review by tianhan0 — APPROVED** [review]

**Comment by bechang** [comment]
@litho17 I don't expect us to push this significantly in the hackathons. But since you're using WALA for your research, please think about how you would transfer things from your own project into cuanto.wala. This is intended to be a starter example for that.

**Pull request merged**
