### PR TITLE
Soot loading only

### PR DESCRIPTION
**Pull request by ftc**

### CODE REVIEW

**Comment by octalsrc** [comment]
What is this [`src/main/scala/Test.scala`](https://github.com/cuplv/cuanto/pull/30/files#diff-7797715a128e687b0b6341913624b551) file for?

**Comment by ftc** [comment]
Did not mean to commit that, I will remove it.

**Comment by octalsrc** [comment]
@cuplv/cuanto I need to get some okays from the rest of the team on this point: the soot loading tests add 30 seconds to the full test suite (justified and unavoidable in that there is a lot of machinery being initialized).  This might be frustrating if you trigger the full test suite often in your dev workflow.

That aside, this looks good and useful! It could use clearer documentation on the main API methods we want to use, but it's straightforward enough to use.

**Comment by octalsrc** [comment]
@smover is going to add "Slow" annotations for filtering the tests.  Until then, we can use `test-only` if they are getting in the way

**Review by octalsrc — APPROVED** [review]

**Comment by smover** [comment]
@octalsrc I tagged the soot tests that take some time to run.
You can run the "fast" tests by using the command `testFast` (it is an alias for `testOnly -- -l...`)

**Comment by octalsrc** [comment]
@smover thanks, can you open a second pull request with that change?

**Pull request merged**
