### PR TITLE
Adding functions to Jsy

### PR DESCRIPTION
**Pull request by bechang**
This pull request is for adding functions to JavaScripty. Function expressions are ready but not calls.

### CODE REVIEW

**Comment by bechang** [comment]
@bennostein @kyleheadley Could you guys review this PR? The documentation could be better, but perhaps you guys could identify the parts that are most confusing?

**Review by kyleheadley — CHANGES_REQUESTED** [review]
In each review, I keep saying to myself, "This is fine, but does it work?", followed immediately by "of course it works", because Evan is pretty good about testing and caring about details. But with the complexity increasing, the question is getting harder to defend.

I'd like to see some kind of "integration tests", demonstrating that the composable units do in fact compose properly, both when a string should parse and when it shouldn't. Is the order of operations reasonable for a function call that is provided multiple expressions as a parameters? Will a typo cause an error or a confusing alternate parsing?

I'm also wondering if someone else can make this work. The abstraction boundaries are not always clear: sequencing is with binding, blocks and parens are with binary ops. There are parsers that are meant to be overloaded, and it may be difficult to understand what other effects the overloading will have outside of the current package.

Overall, I think that this work is internally consistent and makes good progress towards its goals. I think it's a great research project. But one of the stated overarching goals is for this to be a tool for others to use to advance their research projects. I'm having trouble seeing a simple external API that those users will be working with. Good documentation can help, but it can only go so far.

I'm checking the "Request changes" box, requesting tests that combine multiple parser packages. Otherwise, the code meets the quality precedent we've been working with. My other comments are just things to think about.

**Comment by bechang** [comment]
@kyleheadley I have had similar concerns about this. In fact, I written exactly such integration modules (`primitives` and `lambda`) that simply define a composed language. The `lambda` language is the first of our main languages. I have been thinking a restructuring is needed to separate the "component" modules from the "core calculi" that we set out to build (e.g., `functions` is a "component", `lambda` is the "core calculi" with functions, booleans, and numbers). I don't think I know how to do that yet. Take a look at those tests: I think that's what you're looking for.

Could they be more exhaustive and better documented? Yes, certainly. But at the same, I am working late nights to try to make sure you guys are not blocked.

On one hand, we are getting stuck on the extensibility of just parsers, which is kind of frustrating. I care less on that being an API that can be re-used than, say, the Soot interface. But your point is well-taken.

**Comment by kyleheadley** [comment]
@bechang Yeah, the jsy component of the project ended up more complicated than anyone expected, I think. I didn't mean to suggest that it wasn't getting done fast enough. Your tests in `primitives` and `lambda` are the type of thing I was looking for, I must have missed them. I guess I was expecting many more cases, like in your other tests. If you think that they cover the common possibilities, than that's fine. I'll find my approve button.

**Review by kyleheadley — APPROVED** [review]

**Comment by bechang** [comment]
@kyleheadley For `primitives` and `lambda`, I fully admit that they're so-so test cases--and no, not exhaustive. I am balancing getting stuff out for you guys and the ideal software engineering. I wanted to at least have the modules there to uncover some issues.

Please contribute tests and see if it breaks stuff!

**Comment by bechang** [comment]
@kyleheadley Thanks for the review. I am going to merge now to keep us moving, but please submit (or update) an issue if there's something that you think can be done longer-term.

**Pull request merged**
