### PR TITLE
Let-binding and other primitive value parsers

### PR DESCRIPTION
**Pull request by kyleheadley**
I modified the arithmetic parser into a string parser. I hope there aren't any copy-paste errors! (it compiles and tests fine)

### CODE REVIEW

**Comment by kyleheadley** [comment]
@bechang I added a base expression parser to handle arbitrary expressions, based on your OpParser for arbitrary binary expressions. Could you take a look since you and @bennostein may need to use it for this iteration of the work on jsy? Thanks!

**Comment by bechang** [comment]
@kyleheadley Let's get #21 merged into develop, pull changes from there into your branch here, and fix any conflicts before merging this PR. Ok?

**Comment by bechang** [comment]
@kyleheadley Following our discussion before spring break, let's have one language module for the rest of the base values. So strings and undefined.

**Comment by bechang** [comment]
Closing this pull request to separate binding from string. Replaced by pull request #23.

**Comment by bechang** [comment]
Closing this pull request to separate binding from string. Replaced by pull request #23.

**Pull request closed without merging**
