### PR TITLE
Numerical constraint language

### PR DESCRIPTION
**Pull request by bechang**
Feature: add numerical constraint language that combines arithmetic and boolean.

@bennostein @kyleheadley I am starting this pull request to start talking about the combinator parsing refactoring. For a while, I think I was fighting the design pattern from the scala-parser-combinators library, whereas I think the intended design is to stack traits until instantiating a singleton at the end.

### CODE REVIEW

**Comment by bechang** [comment]
@bennostein @kyleheadley The last few commits adds the parser that combines arithmetic and boolean, so I think we have something reasonable with modular parsers.

**Comment by bechang** [comment]
@kyleheadley @bennostein Could you guys review this PR?

**Comment by kyleheadley** [comment]
I don't see anything wrong with it. My only warning is about being too generic too soon. But I assume you've had enough experience to know that these changes will be useful as we continue to build off of this base.

**Comment by bennostein** [comment]
It looks mostly good to me, with a couple caveats:

The documentation is somewhat ambiguous and hard to understand in places.  For example, boolean/Parser.scala#38 seems like a typo(artihmetic->boolean),  the JsyParserLike Scaladoc comment doesn't really say anything of substance, I don't understand the grammar in the scaladoc comment for OpParserLike#binary.

While I don't think this is necessarily too generic, there should be much more rigorous documentation for the generic components defined here.  I think I was able to get the gist of what is being done here and understand it fairly well, but it took me a while to get there.  Better documentation would help a lot in that respect.

**Comment by bechang** [comment]
@bennostein @kyleheadley I put a ton more effort in documenting the generic parser components, particular OpParserLike. Please take to see if I can merge into develop.

I really would like to get this in soon to not block you guys.

**Review by kyleheadley — APPROVED** [review]
The documentation here is superior to the previous version.

**Pull request merged**
