### PR TITLE
Add some Java test cases

### PR DESCRIPTION
**Pull request by bechang**
This adds some Java test cases that are part of the test build.

### CODE REVIEW

**Comment by bechang** [comment]
@smover I just want to add some simple Java test cases so that we have something to play with. This look ok to you?

**Review by smover — CHANGES_REQUESTED** [review]
Can you rename the edu.colorado.plv.cuanto.tinyjava to edu.colorado.plv.cuanto.minijava?

(tinyjava seems to exist and is different from minijava http://cobweb.cs.uga.edu/~kochut/teaching/x570/tinyjava/tinyjava.html)

**Comment by bechang** [comment]
Oh, I just wanted to be clear that we weren't necessarily exactly the same as MiniJava. So let's just use a different name all together? Didn't know TinyJava existed (should've Googled).

**Comment by bechang** [comment]
Javita, it is!

**Review by smover — APPROVED** [review]

**Pull request merged**
